### ISSUE TITLE
Enable search on all pages

### ISSUE THREAD

**Issue by bkamapantula** [gramener/gramex-guide#23]
Currently, to search I need to abandon the current page and go to a different page.

Can we extend search utility from [index page](https://learn.gramener.com/guide/) to all pages?

**Comment by sanand0** [comment]
@bkamapantula Good idea.

We need to incorporate [search.js](https://github.com/gramener/gramex-guide/blob/master/search/search.js) and [search.css](https://github.com/gramener/gramex-guide/blob/master/search/search.css) into the navbar in [markdown-template.html](https://github.com/gramener/gramex-guide/blob/master/markdown.template.html).

My main challenge was to figure out *where* to display the search results. Any thoughts? Or any site we can model this on?

**Comment by pratapvardhan** [comment]
I think, we could 
- keep search box for entry and and on submit direct to /search?q=query page like https://pandas.pydata.org/docs/ does
- show a pop up as you use search like https://docs.readthedocs.io/en/stable/index.html

**Comment by bkamapantula** [comment]
in addition to the suggestions by @pratapvardhan, another option is expand-on-click search option that discourse forums have. example: [pi-hole](https://discourse.pi-hole.net/)
