### ISSUE TITLE
Layout broken in some pages

### ISSUE THREAD

**Issue by jaidevd** [gramener/gramex-guide#37]
Some tables in the guide look like this:

![image](https://user-images.githubusercontent.com/1250388/97950942-7e9ad480-1dbe-11eb-869f-a26f6b0c205e.png)

taken from [ModelHandler](https://learn.gramener.com/guide/modelhandler/)

**Comment by sanand0** [comment]
There are 3 pages with tables: -- [auth/](https://learn.gramener.com/guide/auth/), [formhandler/](https://learn.gramener.com/guide/formhandler/) and [modelhandler/](https://learn.gramener.com/guide/modelhandler/).

auth/ seems fine. I'll fix the other two.
