### ISSUE TITLE
PUT is mandatory to create a model in ModelHandler

### ISSUE THREAD

**Issue by jaidevd** [gramener/gramex-guide#38]
But the guide says that even POST can be used.

From [the guide](https://learn.gramener.com/guide/modelhandler/#expose-endpoints),
```
To create a model send a PUT/POST request to /model/<name>/ with the following URL Query Parameters or JSON Body Arguments...
```

But the handler creates new models only on PUT. See [this](https://github.com/gramener/gramex/blob/master/gramex/handlers/modelhandler.py#L118).

Is there a reason why we don't allow POST to create new models?

**Comment by sanand0** [comment]
Since we're deprecating ModelHandler in favor of MLHandler, closing this issue.
