### ISSUE TITLE
Document security errors

### ISSUE THREAD

**Issue by bkamapantula** [gramener/gramex-guide#39]
Applications are tested for security purposes by third parties. We need to document the practices for the benefit of everyone.

@sainathkyasa helped document some of them. I'll create a PR for the same. It can go under [Deploy page, Security section](https://learn.gramener.com/guide/deploy/)

list: https://paper.dropbox.com/doc/Security-practices--A_IkkWi7vM5p9ewpkaIjiPTeAg-4UbHceJbLgbQkCPIUlI8p

**Comment by sanand0** [comment]
@bkamapantula A few comments:

- This duplicates some documentation that exists in other parts of the guide (e.g. disabling directory listing in FileHandler) or belong in other parts of the guide (e.g. adding custom HTTP headers for Content-Security Policy should be in /config/)
- It mentions some practices that are already part of deploy.yaml (e.g. disallowing file types)

I've refactored these into the sa-issue-39 branch.

- [See Anand's changes](https://github.com/gramener/gramex-guide/compare/bk-issue-39...sa-issue-39)
- [See final PR](https://github.com/gramener/gramex-guide/compare/master...sa-issue-39)

What do you think?

**Comment by bkamapantula** [comment]
this looks cleaner @sanand0, thanks!

**Comment by sanand0** [comment]
Great. I've added it to your PR #41 and merged.
