### ISSUE TITLE
Gramex Testing Error

### ISSUE THREAD

**Issue by arkadeep-baksi** [gramener/gramex-guide#58]
In the Gramex Guide, Testing Section :- After creating gramextest.yaml and running pytest -s -v gives the error :--
"Direct Construction of YamlFile has been deprecated, please use YamlFile.from_parent" . 
The screenshot of the error is given:-
https://www.dropbox.com/s/zz6qieu72n2083v/Gramex_Test_Error.jpeg?dl=0

**Comment by sanand0** [comment]
Deprecate gramextest.

**Comment by sanand0** [comment]
Closed via https://github.com/gramener/gramex/commit/6a0845a
