### ISSUE TITLE
Dashboard Tutorial File Missing

### ISSUE THREAD

**Issue by arkadeep-baksi** [gramener/gramex-guide#59]
In the Gramex Guide , the Dashboard Tutorial link :- https://learn.gramener.com/guide/tutorials/dashboard  
shows File Missing. 
However just in the next Section that is the "Charts Tutorial" , there is a link of reference to the "previous" tutorial or the Dashboard Tutorial. 
There the link to the Dasboard Tutorial is working. I am pasting the correct link of the Dashboard Tutorial here, please update the incorrect link :-
https://learn.gramener.com/guide/tutorials/dashboards/

**Comment by bkamapantula** [comment]
adding a note for reference as I couldn't find a broken link in the main body of the Tutorial

the link in question is in the left panel (Dashboard tutorial):

![image](https://user-images.githubusercontent.com/1143687/109756945-c3a20c80-7be0-11eb-9b08-8add9ecfa72e.png)
