### ISSUE TITLE
Update g1 urlfilter link in Tutorial

### ISSUE THREAD

**Issue by bkamapantula** [gramener/gramex-guide#62]
Tutorial link: https://learn.gramener.com/guide/tutorials/dashboards/

We can update urlchange link in [Step 2](https://learn.gramener.com/guide/tutorials/dashboards/#step-2-detecting-changes-in-the-url) to [g1 doc page](https://learn.gramener.com/guide/g1/urlchange) instead of its [source code page](https://code.gramener.com/cto/g1/blob/master/docs/urlchange.md).

**Comment by bkamapantula** [comment]
PR: #65

**Comment by sanand0** [comment]
Closed via PR merge
