### ISSUE TITLE
Languagetool endpoint is broken

### ISSUE THREAD

**Issue by bkamapantula** [gramener/gramex-guide#63]
Language tool link - https://learn.gramener.com/guide/languagetool/

The link in the text "This mounts the app at languagetool/." is broken (error on Java) which is the below:
 
https://learn.gramener.com/guide/languagetool/languagetool/

![image](https://user-images.githubusercontent.com/1143687/109759047-5c865700-7be4-11eb-8e60-1d7efe864778.png)

**Comment by jaidevd** [comment]
@sanand0 This means that we need to install java on learn.gramener.com.

**Comment by sanand0** [comment]
@jaidevd -- done

```
$ java -version
openjdk version "13.0.2" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.2+8)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13.0.2+8, mixed mode, sharing)
```

**Comment by jaidevd** [comment]
Thanks, @sanand0 
The [languagetool page](https://learn.gramener.com/guide/languagetool/) works now.
