### ISSUE TITLE
In Seaborn v0.11.0 lvplot is updated to boxenplot - Formhandler charts

### ISSUE THREAD

**Issue by bkamapantula** [gramener/gramex-guide#64]
reference: https://seaborn.pydata.org/whatsnew.html?highlight=lvplot#deprecations-and-removals

lvplot is currently used in the [Categorical Plots](https://learn.gramener.com/guide/formhandler/#categorical-plots) section -- last but one chart.

It works fine on the server now but is broken on my local. I use seaborn v0.11.1.

**Comment by bkamapantula** [comment]
PR: #65

**Comment by sanand0** [comment]
Closed via 850a6f9
