### ISSUE TITLE
Windows Offline Install does not work as per instructions 

### ISSUE THREAD

**Issue by bhatsandeep** [gramener/gramex-guide#66]
The path should be: D:\gramex-offline\envs\gramex\**Scripts**\gramex instead of D:\gramex-offline\envs\gramex\**bin**\gramex

![Windows Offline install](https://user-images.githubusercontent.com/67497603/109942673-6f8b4b00-7cfa-11eb-89db-439041254b12.PNG)

**Comment by jaidevd** [comment]
Activation of the right environment on the target machine is critical. After unzipping Gramex on the target machine, we can't just up and run Gramex like "C:\offline\Scripts\gramex.exe" - that just blindly runs the Gramex script while ignoring everything else in the environment.

### Step 1

Initialize the conda shell by running:

```cmd
> D:\offline\Scripts\conda.exe init cmd.exe
```

Exit and restart the shell.

### Step 2

Activate the base environment:

```cmd
> conda activate base
```
If Gramex is installed in the base environment - we're done, and Gramex should work as expected. If Gramex is not in the base environment, proceed to the next step

### Step 3

Activate the environment in which Gramex is installed
```cmd
> conda activate gramexenv
```
Start Gramex.

**Comment by jaidevd** [comment]
@bhatsandeep other than `Scripts\gramex` being named `bin\gramex` - what other issues did you notice?

**Comment by jaidevd** [comment]
From [Anaconda documentation](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#activating-an-environment):

> Windows is extremely sensitive to proper activation. This is because the Windows library loader does not support the concept of libraries and executables that know where to search for their dependencies (RPATH). Instead, Windows relies on a dynamic-link library search order.

> If environments are not active, libraries won't be found and there will be lots of errors. HTTP or SSL errors are common errors when the Python in a child environment can't find the necessary OpenSSL library.

> Conda itself includes some special workarounds to add its necessary PATH entries. This makes it so that it can be called without activation or with any child environment active. In general, calling any executable in an environment without first activating that environment will likely not work. For the ability to run executables in activated environments, you may be interested in the conda run command.

This, I suspect is the problem in the screenshot that @bhatsandeep shared. Let's debug once with the proper activation procedure, and if it works, we'll add these steps to the guide.

**Comment by bhatsandeep** [comment]
@Jaidev Deshpande ***@***.***> that was the only
observed issue as far as getting the path of gramex installation was
concerned. The other issue is the one you're already looking into.
