### ISSUE TITLE
Gramex Upgrade Error

### ISSUE THREAD

**Issue by arkadeep-baksi** [gramener/gramex-guide#68]
When I am running "pip install --upgrade gramex" to update gramex via pip i am getting the following error(Screenshot attached):-https://www.dropbox.com/s/46yt5e7eim1uxx6/Update_Error.png?dl=0

**Comment by jaidevd** [comment]
@arkadeep-baksi What is the Python version you are using? I saw a Python 3.9 somewhere in the screenshot you provided. Can you try with Python 3.7?

**Comment by jaidevd** [comment]
From the screenshot, seems like setuptools needs VS build tools - which indicates that this is a non-conda environment. We do support pip installs, but even those are supported within conda environments. Secondly, this is on Python 3.9.2.

Closing until we know more.

**Comment by arkadeep-baksi** [comment]
Hi Jaidev,

Thanks for reaching out. You are correct this is a non-conda environment
where I have installed gramex via pip. However in conda where the python
version is 3.7 the update command does not give any error.
Hope this helps you

**Comment by vani18110** [comment]
Hi @jaidevd  we want to use the gramformer package for spell check and grammer check.
While installing on conda environment with python 3.9.4 we are facing the package LM score is not getting installed.

As part of it we have downgraded the python version to 3.7.11 and used non conda environment.
But few of the packages are failing to install

**Comment by jaidevd** [comment]
Hi @vani18110 

For Gramformer, please raise your issues here: https://github.com/PrithivirajDamodaran/Gramformer

Thanks,

**Comment by vani18110** [comment]
Hi ,

Can i get the mail id .
Iam not able to put the comment.

Thanks
Vani

**Comment by jaidevd** [comment]
Sorry, @vani18110, Gramformer is a different repository managed by a different organisation or user. We, Gramex, are not connected with it in any way.

PS, if you need to file an issue, look for the issues tab on the Gramformer repository.

**Comment by vani18110** [comment]
Thank you for the clarification.
