### ISSUE TITLE
MLHandler - model.pkl isn't served by default

### ISSUE THREAD

**Issue by bkamapantula** [gramener/gramex-guide#84]
Documentation links model.pkl to be downloaded in this section: https://learn.gramener.com/guide/mlhandler/#exposing-existing-models

this isn't available by default in the repository and no instructions are provided to create it.

**Comment by jaidevd** [comment]
@bkamapantula It gets created automatically when Gramex starts - with this handler: https://github.com/gramener/gramex-guide/blob/master/mlhandler/gramex.yaml#L7

Is that not happening?

**Comment by jaidevd** [comment]
Closing this, @bkamapantula confirmed this works.

**Comment by bkamapantula** [comment]
Sorry, should've commented here. Thanks @jaidevd!
